import React, { useState, useEffect } from 'react';
import api from '../utils/api';
import Layout from '../components/Layout';
import { FileText, Download, Wand2 } from 'lucide-react';

const Reports = () => {
    const [reports, setReports] = useState([]);
    const [generating, setGenerating] = useState(false);

    const fetchReports = async () => {
        try {
            const { data } = await api.get('/reports');
            setReports(data);
        } catch (error) {
            console.error(error);
        }
    };

    useEffect(() => {
        fetchReports();
    }, []);

    const generateReport = async (type) => {
        setGenerating(true);
        try {
            await api.post('/reports', { type });
            fetchReports();
        } catch (error) {
            console.error('Error generating report:', error);
            alert('Failed to generate report');
        } finally {
            setGenerating(false);
        }
    };

    const handlePrint = (report) => {
        const printWindow = window.open('', '', 'width=800,height=600');
        printWindow.document.write(`
            <html>
                <head>
                    <title>${report.type.toUpperCase()} Report - ${new Date(report.generatedAt).toLocaleDateString()}</title>
                    <style>
                        body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
                        h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
                        pre { white-space: pre-wrap; background: #f4f4f4; padding: 20px; border-radius: 5px; }
                        .footer { margin-top: 40px; font-size: 12px; color: #888; text-align: center; }
                    </style>
                </head>
                <body>
                    <h1>${report.type.charAt(0).toUpperCase() + report.type.slice(1)} Performance Report</h1>
                    <p><strong>Date Generated:</strong> ${new Date(report.generatedAt).toLocaleString()}</p>
                    <hr />
                    <h3>Summary</h3>
                    <pre>${report.summaryText}</pre>
                    <div class="footer">
                        Generated by Automated Documentation Generator
                    </div>
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
        printWindow.close();
    };

    return (
        <Layout>
            <div className="flex justify-between items-center mb-8">
                <h1 className="text-3xl font-bold text-gray-800">Documentation & Reports</h1>
            </div>

            {/* Generators */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
                {['daily', 'weekly', 'monthly'].map((type) => (
                    <div key={type} className="bg-white p-6 rounded-lg shadow-sm border border-gray-100 hover:shadow-md transition">
                        <div className="flex items-center justify-between mb-4">
                            <h3 className="text-xl font-semibold capitalize bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                                {type} Report
                            </h3>
                            <FileText className="text-blue-500 opacity-50" size={24} />
                        </div>
                        <p className="text-sm text-gray-500 mb-6">
                            Generate AI-summarized documentation for your {type} activities and productivity.
                        </p>
                        <button
                            onClick={() => generateReport(type)}
                            disabled={generating}
                            className="w-full py-2 px-4 bg-gray-900 text-white rounded-lg hover:bg-gray-800 flex items-center justify-center gap-2 transition disabled:opacity-50"
                        >
                            <Wand2 size={16} />
                            {generating ? 'Generating...' : 'Generate Now'}
                        </button>
                    </div>
                ))}
            </div>

            {/* Recent Reports List */}
            <div className="bg-white rounded-lg shadow-sm overflow-hidden">
                <div className="p-6 border-b border-gray-100">
                    <h2 className="text-lg font-semibold text-gray-800">Recent Generated Documents</h2>
                </div>
                <div className="divide-y divide-gray-100">
                    {reports.length > 0 ? (
                        reports.map((report) => (
                            <div key={report._id} className="p-6 flex items-center justify-between hover:bg-gray-50 transition">
                                <div className="flex items-center gap-4">
                                    <div className="p-3 bg-blue-50 text-blue-600 rounded-lg">
                                        <FileText size={20} />
                                    </div>
                                    <div>
                                        <h4 className="font-semibold text-gray-800 capitalize">
                                            {report.type} Performance Report
                                        </h4>
                                        <p className="text-sm text-gray-500">
                                            Generated on {new Date(report.generatedAt).toLocaleDateString()} at {new Date(report.generatedAt).toLocaleTimeString()}
                                        </p>
                                    </div>
                                </div>
                                <button
                                    onClick={() => handlePrint(report)}
                                    className="flex items-center gap-2 px-4 py-2 border border-gray-200 rounded-lg text-gray-600 hover:bg-white hover:border-gray-300 transition"
                                >
                                    <Download size={16} />
                                    Export PDF
                                </button>
                            </div>
                        ))
                    ) : (
                        <div className="p-10 text-center text-gray-400">
                            No reports generated yet.
                        </div>
                    )}
                </div>
            </div>
        </Layout>
    );
};

export default Reports;
