import React, { useState, useEffect } from 'react';
import api from '../utils/api';
import Layout from '../components/Layout';
import { FileText, Download, Wand2, Zap } from 'lucide-react';

const Reports = () => {
    const [reports, setReports] = useState([]);
    const [generating, setGenerating] = useState(false);

    const fetchReports = async () => {
        try {
            const { data } = await api.get('/reports');
            setReports(data);
        } catch (error) {
            console.error(error);
        }
    };

    useEffect(() => {
        fetchReports();
    }, []);

    const generateReport = async (type) => {
        setGenerating(true);
        try {
            await api.post('/reports', { type });
            fetchReports();
        } catch (error) {
            console.error('Error generating report:', error);
            alert('Failed to generate report');
        } finally {
            setGenerating(false);
        }
    };

    const handlePrint = (report) => {
        const printWindow = window.open('', '', 'width=800,height=600');
        printWindow.document.write(`
            <html>
                <head>
                    <title>${report.type.toUpperCase()} Report - ${new Date(report.generatedAt).toLocaleDateString()}</title>
                    <style>
                        body { font-family: Arial, sans-serif; padding: 40px; line-height: 1.6; }
                        h1 { color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }
                        pre { white-space: pre-wrap; background: #f4f4f4; padding: 20px; border-radius: 5px; }
                        .footer { margin-top: 40px; font-size: 12px; color: #888; text-align: center; }
                    </style>
                </head>
                <body>
                    <h1>${report.type.charAt(0).toUpperCase() + report.type.slice(1)} Performance Report</h1>
                    <p><strong>Date Generated:</strong> ${new Date(report.generatedAt).toLocaleString()}</p>
                    <hr />
                    <h3>Summary</h3>
                    <pre>${report.summaryText}</pre>
                    <div class="footer">
                        Generated by Automated Documentation Generator
                    </div>
                </body>
            </html>
        `);
        printWindow.document.close();
        printWindow.focus();
        printWindow.print();
        printWindow.close();
    };

    return (
        <Layout>
            <div className="flex justify-between items-end mb-10">
                <div>
                    <h1 className="text-4xl font-extrabold text-white tracking-tight mb-2">
                        Analytics <span className="text-gradient">& Reports</span>
                    </h1>
                    <p className="text-slate-400 font-medium">Export high-fidelity documentation synthesized by system logs.</p>
                </div>
                <div className="p-3 glass-card border-white/5 bg-white/5">
                    <FileText className="text-indigo-400" size={24} />
                </div>
            </div>

            {/* Generators */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-10">
                {['daily', 'weekly', 'monthly'].map((type) => (
                    <div key={type} className="glass-card p-8 border-white/5 group hover:bg-white/5 transition-all duration-500">
                        <div className="flex items-center justify-between mb-6">
                            <div className="p-3 bg-indigo-500/10 rounded-2xl text-indigo-400 group-hover:scale-110 transition-transform">
                                <Wand2 size={24} />
                            </div>
                            <span className="text-[10px] font-black text-slate-500 uppercase tracking-[0.2em]">{type} cycle</span>
                        </div>
                        <h3 className="text-xl font-bold text-white capitalize mb-2">
                            {type} Pulse
                        </h3>
                        <p className="text-sm text-slate-500 mb-8 font-medium leading-relaxed">
                            Generate an intelligence summary of your dev activities and milestone velocity.
                        </p>
                        <button
                            onClick={() => generateReport(type)}
                            disabled={generating}
                            className="w-full btn-primary flex items-center justify-center gap-3 disabled:opacity-50 disabled:grayscale"
                        >
                            <Zap size={18} fill="currentColor" />
                            <span className="font-bold">{generating ? 'Synthesizing...' : 'Generate Node'}</span>
                        </button>
                    </div>
                ))}
            </div>

            {/* Recent Reports List */}
            <div className="glass-card border-white/5 overflow-hidden shadow-2xl">
                <div className="p-8 border-b border-white/5 bg-white/5 flex items-center justify-between">
                    <h2 className="text-lg font-bold text-white tracking-tight">Recent Archives</h2>
                    <span className="px-3 py-1 bg-indigo-500/10 text-indigo-400 text-[10px] font-black uppercase rounded-full border border-indigo-500/20">
                        {reports.length} Records Found
                    </span>
                </div>
                <div className="divide-y divide-white/5">
                    {reports.length > 0 ? (
                        reports.map((report) => (
                            <div key={report._id} className="p-8 flex items-center justify-between hover:bg-white/5 transition-all group">
                                <div className="flex items-center gap-6">
                                    <div className="p-4 bg-slate-900 rounded-2xl border border-white/5 text-slate-400 group-hover:text-indigo-400 group-hover:border-indigo-500/30 transition-all">
                                        <FileText size={24} />
                                    </div>
                                    <div>
                                        <h4 className="font-bold text-white capitalize text-lg tracking-tight">
                                            {report.type} Performance Summary
                                        </h4>
                                        <p className="text-sm text-slate-500 font-medium">
                                            Archived on {new Date(report.generatedAt).toLocaleDateString()} at {new Date(report.generatedAt).toLocaleTimeString()}
                                        </p>
                                    </div>
                                </div>
                                <button
                                    onClick={() => handlePrint(report)}
                                    className="flex items-center gap-3 px-6 py-3 border border-white/10 rounded-2xl text-slate-300 hover:text-white hover:bg-white/10 hover:border-white/20 transition-all font-bold text-sm"
                                >
                                    <Download size={18} />
                                    Export PDF
                                </button>
                            </div>
                        ))
                    ) : (
                        <div className="p-20 text-center">
                            <FileText size={48} className="mx-auto text-slate-800 mb-4 opacity-50" />
                            <p className="text-slate-600 font-bold text-xs uppercase tracking-widest">No archives found in storage.</p>
                        </div>
                    )}
                </div>
            </div>
        </Layout>

    );
};

export default Reports;
